[metadata]
format.version = "1.1"

[versions]
assertj = "3.26.3"
junit = "1.11.3"
jupiter = "5.11.3"
okhttp = "4.12.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-suite-engine", version.ref = "junit" }
markdown-gen = { module = "net.steppschuh.markdowngenerator:markdowngenerator", version = "1.3.1.1" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
plantuml = { module = "net.sourceforge.plantuml:plantuml", version = "1.2024.8" }

[plugins]
nexuspublishing = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }