#
#  Copyright (c) 2024 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#    https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#    Bayerische Motoren Werke Aktiengesellschaft (BMW AG) - initial API and implementation
#

---
name: Release

on:
  workflow_call:

jobs:

  create-tag:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.set-version.outputs.VERSION }}
      TAG: ${{ steps.set-tag.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4
      - id: set-version
        run: |
          VERSION=$(echo ${{ github.ref_name }} | cut -d '/' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: eclipse-dataspacetck/tck-common/.github/actions/set-project-version@main
        with:
          version: ${{ steps.set-version.outputs.VERSION }}
      - shell: bash
        id: set-tag
        run: |
          git config user.name "eclipse-dataspacetck-bot"
          git config user.email "dataspacetck-bot@eclipse.org"
          
          TAG=v${{ steps.set-version.outputs.VERSION }}

          git add .
          git commit -m "Release Version $TAG" 

          git tag $TAG
          git push --atomic origin ${{ github.ref_name }} $TAG
          
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

  publish-release-version:
    name: "Publish artefacts to MavenCentral"
    runs-on: ubuntu-latest
    needs: [ create-tag ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.create-tag.outputs.TAG }} # checkout the tag created in the previous step
      - uses: eclipse-dataspacetck/tck-common/.github/actions/publish-maven-artifacts@main
        with:
          version: ${{ needs.create-tag.outputs.VERSION }} # explicitly pass the version
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          osshr-username: ${{ secrets.OSSRH_USERNAME }}
          osshr-password: ${{ secrets.OSSRH_PASSWORD }}

  create-github-release:
    needs: [ create-tag, publish-release-version ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ needs.create-tag.outputs.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          removeArtifacts: true